package com.xworkz.bridge.airport;

public enum AirportType {

	COMMERCIAL_SERVICE_AIRPORT_PRIMARY,
	COMMERCIAL_SERVICE_AIRPORT_NON_PRIMARY,
	CARGO_SERVICE_AIRPORTS,
	RELIEVER_AIRPORTS,
	GENERAL_AVIATION_AIRPORTS,
	NATIONAL_AIRPORTS,
	REGIONAL_AIRPORTS,
	LOCAL_AIRPORTS,
	INTER_NATIONAL_AIRPORTS;
	
}
