package com.xworkz.object.constants;

public enum HeadsetType {

	CLOSED_BACK_HEADPHONES, OPEN_BACK_HEADPHONES, ON_EAR_HEADPHONES, OVER_EAR_HEADPHONES, 
	IN_EAR_HEADPHONES, EARBUDS, BLUETOOTH_HEADPHONES, NOISE_CANCELLING_HEADPHONES;

}
